robot:
  wheel_distance: 37.3
  speed: 10.0
  pid:
    kp: 28
    ki: 0.02
    kd: 0.5

# TEAM BLUE STRATEGY
# start at goal 22
# goal 29 - pick up cans
# goal 22 - drop off cans
# goal 33 - pick up cans -- handle differently by esp 
# (goal 24 - drop off cans -- reached by esp) 
# goal 35 - pick up cans
# goal 23 - drop off cans
# goal 18 - final position

# goals:
#   - x: 124
#     y: 24
#     theta: 0

#   # Goal 9
#   - x: 60
#     y: 140
#     theta: 0

#   - x: 124
#     y: 24
#     theta: 0


## OPENCV FRAME

goals:
  - x: 125
    y: 170
    theta: -90

  # Goal 9
  - x: 60
    y: 60
    theta: 0

  - x: 125
    y: 170
    theta: -90