robot:
  wheel_distance: 37.3
  speed: 10.0
  pid:
    kp: 28
    ki: 0.02
    kd: 0.5

goals:
  # Goal 0
  - x: 37
    y: 182
    theta: 0

  # Goal 1
  - x: 77
    y: 15
    theta: 180

  # Goal 2
  - x: 122
    y: 15
    theta: 180

  # Goal 3
  - x: 122
    y: 45
    theta: 180

  # Goal 4
  - x: 277
    y: 15
    theta: 180

  # Goal 5
  - x: 285
    y: 87
    theta: 90

  # Goal 6
  - x: 255
    y: 87
    theta: 90

  # Goal 7
  - x: 36
    y: 132
    theta: -90

  # Goal 8
  - x: 110
    y: 124
    theta: 180

  # Goal 9
  - x: 110
    y: 66
    theta: 0

  # Goal 10
  - x: 190
    y: 124
    theta: 180

  # Goal 11
  - x: 190
    y: 66
    theta: 0

  # Goal 12
  - x: 263
    y: 132
    theta: 90

  # Goal 13
  - x: 36
    y: 40
    theta: -90

  # Goal 14
  - x: 77
    y: 54
    theta: 180

  # Goal 15
  - x: 222
    y: 54
    theta: 180

  # Goal 16
  - x: 263
    y: 40
    theta: 90

  # Goal 17
  - x: 82
    y: 144
    theta: 0

  # Goal 18
  - x: 262
    y: 182
    theta: 0

  # Goal 19
  - x: 15
    y: 87
    theta: -90

  # Goal 20
  - x: 45
    y: 87
    theta: -90

  # Goal 21
  - x: 22
    y: 15
    theta: 180

  # Goal 22
  - x: 177
    y: 15
    theta: 180

  # Goal 23
  - x: 177
    y: 45
    theta: 180

  # Goal 24
  - x: 222
    y: 15
    theta: 180

  # Goal 25
  - x: 36
    y: 132
    theta: -90

  # Goal 26
  - x: 110
    y: 124
    theta: 180

  # Goal 27
  - x: 110
    y: 66
    theta: 0

  # Goal 28
  - x: 190
    y: 124
    theta: 180

  # Goal 29
  - x: 190
    y: 66
    theta: 0

  # Goal 30
  - x: 263
    y: 132
    theta: 90

  # Goal 31
  - x: 36
    y: 40
    theta: -90

  # Goal 32
  - x: 77
    y: 54
    theta: 180

  # Goal 33
  - x: 222
    y: 54
    theta: 180

  # Goal 34
  - x: 263
    y: 40
    theta: 90

  # Goal 35
  - x: 217
    y: 144
    theta: 0

  #   # Goal test
  # - x: 0
  #   y: 0
  #   theta: 0

  #   # Goal test
  # - x: 300
  #   y: 200
  #   theta: 0

    # Goal test
  # - x: 150
  #   y: 100
  #   theta: 0