robot:
  wheel_distance: 37.3
  speed: 12.0
  pid:
    kp: 30
    ki: 0.02
    kd: 0.6

# TEAM YELLOW STRATEGY
# start at goal 2
# goal 9 - pick up cans
# goal 2 - drop off cans
# goal 14 - pick up cans -- handle differently by esp 
# (goal 1 - drop off cans -- reached by esp) 
# goal 17 - pick up cans
# goal 3 - drop off cans
# goal 0 - final position

goals:
    # Starting Position (Goal #2)
  - x: 122
    y: 175
    theta: -90

  # # Goal 9
  # - x: 110
  #   y: 133
  #   theta: -90

  #   # Goal 2
  # - x: 122
  #   y: 175
  #   theta: 90

  #   # Goal 14
  # - x: 77
  #   y: 145
  #   theta: 90

  #   # Goal 17
  # - x: 81
  #   y: 65
  #   theta: -90

  #   # Goal 3
  # - x: 122
  #   y: 154
  #   theta: 90

    # Goal 0
  - x: 30
    y: 25
    theta: -90