robot:
  wheel_distance: 37.3
  speed: 20.0
  pid:
    kp: 28
    ki: 0.02
    kd: 0.6


goals:
    # Step = 0
    # Starting Position (Goal #2)  
  - x: 122
    y: 184
    theta: -90

  # Step = 1
  # Goal 9
  - x: 110
    y: 133
    theta: -180

    # Step = 2
    # Goal 14  PUSH CANS STARTING POS
  - x: 77
    y: 132
    theta: -270

    # Step = 3
    # Goal     PUSH CANS (touch planks)
  - x: 77
    y: 170
    theta: -270

      # Step = 4
    # Goal     PUSH CANS END
  - x: 77
    y: 187
    theta: -270

  # MOVE BACKWARDS A LITTLE BIT (esp)


     # Step = 5
    # Goal 7  midpoint
  - x: 50
    y: 55
    theta: -155

    # Step = 6
    # Goal 0
  - x: 32
    y: 30
    theta: -90
