robot:
  wheel_distance: 37.3
  speed: 30.0
  pid:
    kp: 28
    ki: 0.02
    kd: 0.6

# TEAM YELLOW STRATEGY
# start at goal 2
# goal 9 - pick up cans
# goal 2 - drop off cans
# goal 14 - pick up cans -- handle differently by esp 
# (goal 1 - drop off cans -- reached by esp) 
# goal 17 - pick up cans
# goal 3 - drop off cans
# goal 0 - final position

goals:
    # Step = 0
    # Starting Position (Goal #22)  
  - x: 177
    y: 175
    theta: -90

  #   # Step = 1
  #   # Goal 23   midpoint
  # - x: 177
  #   y: 154
  #   theta: -90

  # Step = 1
  # Goal 29
  - x: 190
    y: 133
    theta: 0

    # Step = 2
    # Goal 30  midpoint
  - x: 235
    y: 132
    theta: -80

      # Step = 3
    # Goal 30  midpoint
  - x: 245
    y: 50
    theta: -25


    # Step = 4
    # Goal 18
  - x: 262
    y: 5
    theta: -90