robot:
  wheel_distance: 37.3
  speed: 10.0
  pid:
    kp: 28
    ki: 0.02
    kd: 0.5

# TEAM BLUE STRATEGY
# start at goal 22
# goal 29 - pick up cans
# goal 22 - drop off cans
# goal 33 - pick up cans -- handle differently by esp 
# (goal 24 - drop off cans -- reached by esp) 
# goal 35 - pick up cans
# goal 23 - drop off cans
# goal 18 - final position

goals:
  # Goal 29
  - x: 190
    y: 66
    theta: 0

    # Goal 22
  - x: 177
    y: 15
    theta: 180

    # Goal 33
  - x: 222
    y: 54
    theta: 180

    # Goal 35
  - x: 217
    y: 144
    theta: 0

    # Goal 23
  - x: 177
    y: 45
    theta: 180

    # Goal 18
  - x: 262
    y: 182
    theta: 0