robot:
  wheel_distance: 37.3
  speed: 10.0
  pid:
    kp: 28
    ki: 0.02
    kd: 0.5

# TEAM YELLOW STRATEGY
# start at goal 2
# goal 9 - pick up cans
# goal 2 - drop off cans
# goal 14 - pick up cans -- handle differently by esp 
# (goal 1 - drop off cans -- reached by esp) 
# goal 17 - pick up cans
# goal 3 - drop off cans
# goal 0 - final position

goals:
  # - x: 124
  #   y: 182
  #   theta: 0

  # Goal 9
  - x: 110
    y: 66
    theta: 0

    # Goal 2
  - x: 77
    y: 15
    theta: 180

    # Goal 14
  - x: 77
    y: 54
    theta: 180

    # Goal 17
  - x: 82
    y: 144
    theta: 0

    # Goal 3
  - x: 122
    y: 45
    theta: 180

    # Goal 0
  - x: 37
    y: 182
    theta: 0