robot:
  wheel_distance: 37.3
  speed: 10.0
  pid:
    kp: 28
    ki: 0.02
    kd: 0.5

# TEAM YELLOW STRATEGY
# start at goal 2
# goal 9 - pick up cans
# goal 2 - drop off cans
# goal 14 - pick up cans -- handle differently by esp 
# (goal 1 - drop off cans -- reached by esp) 
# goal 17 - pick up cans
# goal 3 - drop off cans
# goal 0 - final position

goals:
    # Step = 0
    # Starting Position (Goal #2)  
  - x: 122
    y: 175
    theta: -90

  #   # Step = 1
  #   # Goal 3   midpoint
  # - x: 122
  #   y: 154
  #   theta: -90

  # Step = 2
  # Goal 9
  - x: 110
    y: 133
    theta: -90

    # Step = 13
    # Goal 7  midpoint
  - x: 60
    y: 132
    theta: -90

      # Step = 13
    # Goal 7  midpoint
  - x: 60
    y: 50
    theta: -90

    # Step = 14
    # Goal 0
  - x: 37
    y: 25
    theta: -90
