robot:
  wheel_distance: 37.3
  speed: 10.0
  pid:
    kp: 28
    ki: 0.02
    kd: 0.5

# TEAM YELLOW STRATEGY
# start at goal 2
# goal 9 - pick up cans
# goal 2 - drop off cans
# goal 14 - pick up cans -- handle differently by esp 
# (goal 1 - drop off cans -- reached by esp) 
# goal 17 - pick up cans
# goal 3 - drop off cans
# goal 0 - final position


goals:
  - x: 125
    y: 170
    theta: -90

  # Goal 9
  - x: 60
    y: 60
    theta: 0

  - x: 125
    y: 170
    theta: -90