robot:
  wheel_distance: 37.6
  speed: 15.0
  pid:
    kp: 30.0
    ki: 0.01
    kd: 1.0

goals:
  - x: 50
    y: 70
    theta: 0
  - x: 250
    y: 150
    theta: 90
  - x: 60
    y: 100
    theta: -90
  - x: 250
    y: 150
    theta: 90
  - x: 50
    y: 70
    theta: 0
