robot:
  wheel_distance: 37.3
  speed: 30.0
  pid:
    kp: 28
    ki: 0.02
    kd: 0.6


# TEAM BLUE STRATEGY
# start at goal 22
# goal 29 - pick up cans
# goal 22 - drop off cans
# goal 33 - pick up cans -- handle differently by esp 
# (goal 24 - drop off cans -- reached by esp) 
# goal 35 - pick up cans
# goal 23 - drop off cans
# goal 18 - final position

goals:
    # Step = 0
    # Starting Position (Goal #22)  
  - x: 177
    y: 184
    theta: -90

  #   # Step = 1
  #   # Goal 23   midpoint
  # - x: 177
  #   y: 154
  #   theta: -90

  # Step = 1
  # Goal 29
  - x: 190
    y: 133
    theta: -90

  # Step = 2
  # Goal PICK UP CANS (from 29)
  - x: 190
    y: 109
    theta: -90

  # Step = 3
    # Goal 23   midpoint
  - x: 177
    y: 154
    theta: 90

    # Step = 4
    # Goal 22   (DROP OFF CANS)
  - x: 177
    y: 175
    theta: 90

    # Step = 5
    # Goal 23   midpoint
  - x: 177
    y: 154
    theta: -15

    # Step = 6
    # Goal 33    
  - x: 222
    y: 145
    theta: 90

    # Step = 7
    # Goal 33    PICK UP CANS (from 33)
  - x: 222
    y: 171
    theta: 90

    # Step = 8
    # Goal 24     (DROP OFF CANS)
  - x: 222
    y: 184
    theta: 90

    # MOVE BACKWARDS A LITTLE BIT (esp)

  # Step = 9
    # Goal 35
  - x: 217
    y: 65
    theta: -90

    # Step = 10
    # PICK UP CANS (from 35)
  - x: 217
    y: 31
    theta: -90

    # MOVE BACKWARDS A LITTLE BIT MORE (esp)

    # Step = 11
    # Goal 23  (DROP OFF CANS)
  - x: 177
    y: 154
    theta: 90

    # Step = 12
    # Goal 30  midpoint
  - x: 245
    y: 50
    theta: -25

    # Step = 13
    # Goal 18
  - x: 262
    y: 25
    theta: -90

