obstacles:
  - x: 77
    y: 25
    width: 40
    height: 10
    type: "FIXED"
    color: "lightgray"
  - x: 110
    y: 95
    width: 40
    height: 10
    type: "FIXED"
    color: "lightgray"
  - x: 190
    y: 95
    width: 40
    height: 10
    type: "FIXED"
    color: "lightgray"
  - x: 222
    y: 25
    width: 40
    height: 10
    type: "FIXED"
    color: "lightgray"